# Generated by Django 3.0.2 on 2020-01-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(default='clothes', max_length=100)),
                ('categoryDescription', models.CharField(default='shirt', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='productSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='shirt', max_length=100)),
                ('productCategoryId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productCategory', to='home.productCategory')),
            ],
        ),
        migrations.DeleteModel(
            name='catergory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='catergory',
        ),
        migrations.AddField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.productCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategoryId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subCategory', to='home.productSubCategory'),
        ),
    ]
