# Generated by Django 2.2.4 on 2019-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catergory',
            field=models.CharField(default='clothes', max_length=100),
        ),
    ]
